name: rtd
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
      - flask
      - flask-httpauth
      - chameleon
      - multidict
      - isodate
      - scipy
      - metpy
      - markdown
      - xstatic
      - defusedxml
      - sphinx_rtd_theme
      - sphinx
      - fs
      - netCDF4
      - future
      - PyQt5
      - owslib
  - basemap >=1.3.3
  - pint
